install:
  - set QTDIR=C:\Qt\5.7\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
  
build_script:
  - cd C:\projects\CPPWebFramework\CPPWebFramework\cwf
  
  - rename cppwebframework_global.h cppwebframework_global.h.1
  - rename cppwebframework_global.h.2 cppwebframework_global.h
  
  - cd ..
  - qmake UnitTests.pro
  - mingw32-make -j 8
  - release\UnitTests.exe
  - mingw32-make clean
  
  - cd cwf
  - rename cppwebframework_global.h cppwebframework_global.h.2
  - rename cppwebframework_global.h.1 cppwebframework_global.h
  
  - cd ..
  - qmake CPPWebFramework.pro
  - mingw32-make -j 8
  - mingw32-make install
  
  - cd ..
  - cd examples
  - cd HelloWorld
  - qmake HelloWorld.pro
  - mingw32-make -j 8
    
  - cd ..
  - cd ShowFile
  - qmake ShowFile.pro
  - mingw32-make -j 8

  - cd ..
  - cd SaveFiles
  - qmake SaveFiles.pro
  - mingw32-make -j 8

  - cd ..
  - cd Sessions
  - qmake Sessions.pro
  - mingw32-make -j 8

  - cd ..
  - cd Filters
  - qmake Filters.pro
  - mingw32-make -j 8

  - cd ..
  - cd CSTLOutExample
  - qmake CSTLOutExample.pro
  - mingw32-make -j 8

  - cd ..
  - cd CSTLForExample
  - qmake CSTLForExample.pro
  - mingw32-make -j 8

  - cd ..
  - cd CSTLIfExample
  - qmake CSTLIfExample.pro
  - mingw32-make -j 8

  - cd ..
  - cd FillObjectBMI
  - qmake FillObjectBMI.pro
  - mingw32-make -j 8

  - cd ..
  - cd CSTLImportExample
  - qmake CSTLImportExample.pro
  - mingw32-make -j 8

  - cd ..
  - cd WebServices
  - qmake WebServices.pro
  - mingw32-make -j 8

  - cd ..
  - cd CRUDRestWebService
  - qmake CRUDRestWebService.pro
  - mingw32-make -j 8

  - cd ..
  - cd HelloWorldFilter
  - qmake HelloWorldFilter.pro
  - mingw32-make -j 8

  - cd ..
  - cd HelloMVC
  - qmake HelloMVC.pro
  - mingw32-make -j 8

  - cd ..
  - cd RESTWebService
  - qmake RESTWebService.pro
  - mingw32-make -j 8

  - cd ..
  - cd ORM
  - qmake ORM.pro
  - mingw32-make -j 8
